#!/usr/bin/env python3
# workaround for https://bugs.launchpad.net/maas/+bug/2078066
import json
import os
import pprint

USB_INTERFACE_NAME="enxbe3af2b6059f"

def main():
    maas_resource_file = os.environ["MAAS_RESOURCES_FILE"]
    with open(maas_resource_file, 'r') as resources_file:
        data=json.load(resources_file)
    resources_file.close()
    filtered_cards = [] 
    for card in data["resources"]["network"]["cards"]:
        filtered_port=list(filter(lambda port: port["id"] != USB_INTERFACE_NAME, card["ports"]))
        if len(filtered_port) > 0:
            filtered_cards.append(card)
        else:
            print(f"{USB_INTERFACE_NAME} found in resources/networks/cards/port, removing it")
    data["resources"]["network"]["cards"]=filtered_cards
    
    if USB_INTERFACE_NAME in data["networks"].keys():
        del(data["networks"][USB_INTERFACE_NAME])
        print(f"Removing interface {USB_INTERFACE_NAME} from the networks elements")
    else:
        print(f"{USB_INTERFACE_NAME} not found, skipping...")

    data_json = json.dumps(data, indent=4)
    with open(maas_resource_file, 'w') as resources_file:
        resources_file.write(data_json)
    resources_file.close()
#    pprint.pprint(data["networks"])
#    pprint.pprint(data["resources"]["network"]["cards"])


if __name__ == "__main__":
    main()
